name: CakePHP Deploy
on:
    create:
        tags:
            - "*"
jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@master
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: intl, mbstring, simplexml, pdo
            -   name: Install Packages
                run: composer install --no-dev
            -   name: deploy file
                uses: wlixcc/SFTP-Deploy-Action@v1.0
                with:
                    username: 'webmania_hur'
                    server: '87.229.65.46'
                    ssh_private_key: ${{ secrets.SSH_1108_KEY }}
                    local_path: './*'
                    remote_path: '../../web/'
                    args: '-o ConnectTimeout=5'